### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by ghost** [binatify/gin-template#35]
after running the generator:
cd /hello && GO111MODULE=on go run main.go

````
INFO[2019-06-25 15:13:47.451482]/Users/apple/workspace/go/pkg/mod/github.com/binatify/gin-template/base/app@v0.0.0-20190517093307-921b0d63d44d/application.go:51 github.com/binatify/gin-template/base/app.NewApplication() Initialized hello in development mode        
PANI[2019-06-25 15:13:59.032466]/Users/apple/workspace/go/pkg/mod/github.com/binatify/gin-template/base/model@v0.0.0-20190517093307-921b0d63d44d/model.go:42 github.com/binatify/gin-template/base/model.NewModel() no reachable servers                         
panic: (*logrus.Entry) (0x17a41a0,0xc0001cb340)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000084180, 0xc0001d3470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/apple/workspace/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/entry.go:239 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc0001cb2d0, 0xc000000000, 0xc0001edec0, 0x1, 0x1)
        /Users/apple/workspace/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Logger).Log(0xc000084180, 0x0, 0xc0001edec0, 0x1, 0x1)
        /Users/apple/workspace/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/logger.go:192 +0x7f
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /Users/apple/workspace/go/pkg/mod/github.com/sirupsen/logrus@v1.4.1/logger.go:233
github.com/binatify/gin-template/base/model.NewModel(0xc0000840c0, 0xc000084180, 0xc00002e074)
        /Users/apple/workspace/go/pkg/mod/github.com/binatify/gin-template/base/model@v0.0.0-20190517093307-921b0d63d44d/model.go:42 +0x4b6
gin-template/app/models.SetupModelWithConfig(...)
        /Users/apple/workspace/go/src/bitbucket.org/gedw99/centri/archi/v3/ui/datadriven/gin/gintemplate/hello/app/models/model.go:17
gin-template/app/controllers.NewApplication(0x17b64d7, 0xb, 0xc00002e074, 0x66, 0x0)
````

**Comment by songjiayang** [comment]
@gedw99  Sorry late for relay, please check your MongoDB connect with default config.
